name: Pull Request
description: Create a pull request

assignees:
  - MaikoTan

body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to the SD-WebUI Stable Horde Worker Bridge Project!
        Please check the following items before submitting your pull request.

        *You can install flake8 and black that we are using for linting the code with `pip install -r requirements.txt`*

  - type: checkboxes
    attributes:
      label: Checklist
      description: Please make sure you've completed all of the following.
      options:
        - label: I've checked that this isn't a duplicate pull request.
          required: true
        - label: I've tested my changes with the latest SD-Webui version.
          required: true
        - label: "I've format my code with [black](https://black.readthedocs.io/): `black .`"
          required: true
        - label: "I've lint my code with [flake8](https://flake8.pycqa.org/): `flake8 .`"
          required: true
        - label: I've read the [Contribution Guidelines](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/blob/master/CONTRIBUTING.md)
          required: true
        - label: I've read the [Code of Conduct](https://github.com/sdwebui-w-horde/sd-webui-stable-horde-worker/blob/master/CODE_OF_CONDUCT.md)
          required: true


  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What type of change is this?
      multiple: true
      options:
        - Bugfix
        - Feature
        - Refactoring
        - Optimization
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe your changes.
    validations:
      required: true
