name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please make sure to fill out the form below.

  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: Is there existing issue for this?
      description: Please search to see if an issue already exists for the feature you are suggesting, also checked the latest commit to make sure this feature is still not implemented.
      options:
        - label: I didn't find similar issue, also checked the latest commit.
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of what the feature is.
      placeholder: Tell us what you want!
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: A clear and concise description of how do you implement this feature.
      placeholder: Tell us how you want it to work!
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        Add any other context or screenshots about the feature request here.
